export const SEED_PILLS = [
  {
    imprint: 'L484',
    color: 'White',
    shape: 'Capsule/Oblong',
    drug_name: 'Acetaminophen',
    generic_name: 'Acetaminophen',
    strength: '500 mg',
    drug_class: 'Miscellaneous analgesics',
    uses: 'Pain, Fever, Sciatica, Muscle Pain, Chronic Pain, Back Pain',
    image_url: 'https://www.drugs.com/images/pills/mtm/L484.JPG',
  },
  {
    imprint: 'M367',
    color: 'White',
    shape: 'Capsule/Oblong',
    drug_name: 'Acetaminophen and Hydrocodone Bitartrate',
    generic_name: 'Acetaminophen / Hydrocodone',
    strength: '325 mg / 10 mg',
    drug_class: 'Narcotic analgesic combinations',
    uses: 'Back Pain, Pain, Cough',
    image_url: null,
  },
  {
    imprint: 'L612',
    color: 'White',
    shape: 'Round',
    drug_name: 'Loratadine',
    generic_name: 'Loratadine',
    strength: '10 mg',
    drug_class: 'Antihistamines',
    uses: 'Allergies, Hay Fever',
    image_url: null,
  },
  {
    imprint: 'G037',
    color: 'White',
    shape: 'Capsule/Oblong',
    drug_name: 'Lortab',
    generic_name: 'Acetaminophen / Hydrocodone',
    strength: '500 mg / 5 mg',
    drug_class: 'Narcotic analgesic combinations',
    uses: 'Pain, Cough',
    image_url: null,
  },
  {
    imprint: 'K56',
    color: 'Blue',
    shape: 'Round',
    drug_name: 'Oxycodone Hydrochloride',
    generic_name: 'Oxycodone',
    strength: '10 mg',
    drug_class: 'Opioids',
    uses: 'Pain',
    image_url: null,
  },
  {
    imprint: 'M523',
    color: 'White',
    shape: 'Capsule/Oblong',
    drug_name: 'Acetaminophen and Oxycodone Hydrochloride',
    generic_name: 'Acetaminophen / Oxycodone',
    strength: '325 mg / 10 mg',
    drug_class: 'Narcotic analgesic combinations',
    uses: 'Pain',
    image_url: null,
  },
  {
    imprint: 'M366',
    color: 'White',
    shape: 'Capsule/Oblong',
    drug_name: 'Acetaminophen and Hydrocodone Bitartrate',
    generic_name: 'Acetaminophen / Hydrocodone',
    strength: '325 mg / 7.5 mg',
    drug_class: 'Narcotic analgesic combinations',
    uses: 'Pain, Cough',
    image_url: null,
  },
  {
    imprint: 'TEVA3926',
    color: 'White',
    shape: 'Round',
    drug_name: 'Diazepam',
    generic_name: 'Diazepam',
    strength: '5 mg',
    drug_class: 'Benzodiazepines',
    uses: 'Anxiety, Muscle Spasm, Seizures',
    image_url: null,
  },
  {
    imprint: 'AN627',
    color: 'White',
    shape: 'Capsule/Oblong',
    drug_name: 'Tramadol Hydrochloride',
    generic_name: 'Tramadol',
    strength: '50 mg',
    drug_class: 'Opioids',
    uses: 'Pain',
    image_url: null,
  },
  {
    imprint: 'L194',
    color: 'White',
    shape: 'Round',
    drug_name: 'Famotidine',
    generic_name: 'Famotidine',
    strength: '20 mg',
    drug_class: 'H2 antagonists',
    uses: 'GERD, Stomach Ulcers, Heartburn',
    image_url: null,
  },
  {
    imprint: 'I2',
    color: 'White',
    shape: 'Round',
    drug_name: 'Ibuprofen',
    generic_name: 'Ibuprofen',
    strength: '200 mg',
    drug_class: 'NSAIDs',
    uses: 'Pain, Fever, Inflammation',
    image_url: null,
  },
  {
    imprint: '12',
    color: 'White',
    shape: 'Round',
    drug_name: 'Clonazepam',
    generic_name: 'Clonazepam',
    strength: '0.5 mg',
    drug_class: 'Benzodiazepines',
    uses: 'Anxiety, Seizures',
    image_url: null,
  },
  {
    imprint: '4H2',
    color: 'White',
    shape: 'Round',
    drug_name: 'Cetirizine Hydrochloride',
    generic_name: 'Cetirizine',
    strength: '10 mg',
    drug_class: 'Antihistamines',
    uses: 'Allergies, Hay Fever',
    image_url: null,
  },
  {
    imprint: 'R180',
    color: 'White',
    shape: 'Capsule/Oblong',
    drug_name: 'Tizanidine Hydrochloride',
    generic_name: 'Tizanidine',
    strength: '4 mg',
    drug_class: 'Skeletal muscle relaxants',
    uses: 'Muscle Spasm',
    image_url: null,
  },
  {
    imprint: 'R029',
    color: 'White',
    shape: 'Round',
    drug_name: 'Alprazolam',
    generic_name: 'Alprazolam',
    strength: '0.5 mg',
    drug_class: 'Benzodiazepines',
    uses: 'Anxiety, Panic Disorder',
    image_url: null,
  },
  {
    imprint: 'TV58',
    color: 'White',
    shape: 'Round',
    drug_name: 'Tramadol',
    generic_name: 'Tramadol',
    strength: '50 mg',
    drug_class: 'Opioids',
    uses: 'Pain',
    image_url: null,
  },
  {
    imprint: '022',
    color: 'White',
    shape: 'Round',
    drug_name: 'Cyclobenzaprine Hydrochloride',
    generic_name: 'Cyclobenzaprine',
    strength: '10 mg',
    drug_class: 'Skeletal muscle relaxants',
    uses: 'Muscle Spasm',
    image_url: null,
  },
  {
    imprint: 'H49',
    color: 'White',
    shape: 'Capsule/Oblong',
    drug_name: 'Sulfamethoxazole and Trimethoprim',
    generic_name: 'Sulfamethoxazole / Trimethoprim',
    strength: '800 mg / 160 mg',
    drug_class: 'Sulfonamides',
    uses: 'Bacterial Infections',
    image_url: null,
  },
  {
    imprint: '031R',
    color: 'White',
    shape: 'Oval',
    drug_name: 'Alprazolam',
    generic_name: 'Alprazolam',
    strength: '0.25 mg',
    drug_class: 'Benzodiazepines',
    uses: 'Anxiety, Panic Disorder',
    image_url: null,
  },
  {
    imprint: 'TEVA3925',
    color: 'White',
    shape: 'Round',
    drug_name: 'Diazepam',
    generic_name: 'Diazepam',
    strength: '2 mg',
    drug_class: 'Benzodiazepines',
    uses: 'Anxiety, Muscle Spasm',
    image_url: null,
  },
  {
    imprint: '377',
    color: 'White',
    shape: 'Capsule/Oblong',
    drug_name: 'Tramadol Hydrochloride',
    generic_name: 'Tramadol',
    strength: '50 mg',
    drug_class: 'Opioids',
    uses: 'Pain',
    image_url: null,
  },
  {
    imprint: 'C230',
    color: 'White',
    shape: 'Capsule/Oblong',
    drug_name: 'Acetaminophen and Oxycodone Hydrochloride',
    generic_name: 'Acetaminophen / Oxycodone',
    strength: '325 mg / 5 mg',
    drug_class: 'Narcotic analgesic combinations',
    uses: 'Pain',
    image_url: null,
  },
  {
    imprint: 'I10',
    color: 'White',
    shape: 'Oval',
    drug_name: 'Ibuprofen',
    generic_name: 'Ibuprofen',
    strength: '200 mg',
    drug_class: 'NSAIDs',
    uses: 'Pain, Fever, Inflammation',
    image_url: null,
  },
  {
    imprint: '123',
    color: 'White',
    shape: 'Round',
    drug_name: 'Ibuprofen',
    generic_name: 'Ibuprofen',
    strength: '200 mg',
    drug_class: 'NSAIDs',
    uses: 'Pain, Fever',
    image_url: null,
  },
  {
    imprint: 'G 12',
    color: 'White',
    shape: 'Oval',
    drug_name: 'Metformin Hydrochloride',
    generic_name: 'Metformin',
    strength: '1000 mg',
    drug_class: 'Non-sulfonylureas',
    uses: 'Type 2 Diabetes',
    image_url: null,
  },
];
